name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-macros-plugin mkdocs-awesome-pages-plugin mkdocs-redirects
      - run: mkdocs gh-deploy --force
      - run: git checkout gh-pages
      - run: export CI_PAGES_URL="https://$GITHUB_ACTOR.github.io/$( cut -d '/' -f 2- <<< "$GITHUB_REPOSITORY" )/"; echo $CI_PAGES_URL;
      - run: for file in $(find * -name "*.html"); do sed -i "s|<img \([^\\\>]*\)src=\"\([^\:]*\)\"|<img \1\src=\"$CI_PAGES_URL/$(dirname $file)/\2\"|g" $file; done
      - run: GIT_AUTHOR_EMAIL="benoit.rospars@inria.fr" && GIT_AUTHOR_NAME="Benoit Rospars" && git add . && git commit -m "Relative to absolute urls"
